INSERT INTO departments (department_name, manager_id)
VALUES 
('Human Resources', 1),
('Engineering', 2),
('Sales', 3),
('Marketing', 4),
('Finance', 5),
('Customer Support', 6),
('IT', 7),
('Research and Development', 8),
('Legal', 9),
('Administration', 10),
('Operations', 11),
('Public Relations', 12),
('Procurement', 13),
('Security', 14),
('Facilities', 15),
('Product Management', 16),
('Quality Assurance', 17),
('Training', 18),
('Compliance', 19),
('Project Management', 20),
('Business Intelligence', 21),
('Logistics', 22),
('Consulting', 23),
('Design', 24),
('Strategy', 25),
('Content Management', 26),
('Partnerships', 27),
('Supply Chain', 28),
('Investor Relations', 29),
('Risk Management', 30),
('Audit', 31),
('Legal Affairs', 32),
('Ethics and Compliance', 33),
('Corporate Affairs', 34),
('Health and Safety', 35),
('Manufacturing', 36),
('HR Development', 37),
('Corporate Strategy', 38),
('Business Development', 39),
('Accounting', 40),
('Financial Planning', 41),
('Merchandising', 42),
('Innovation', 43),
('Customer Experience', 44),
('Vendor Management', 45),
('Environmental Health', 46),
('Media Relations', 47),
('Customer Success', 48),
('E-Commerce', 49),
('Internal Communications', 50);
